"""EKI TCP/XML protocol constants for path execution (coctrl_eki)."""

DEFAULT_PATH_ROBOT_PORT = 54603
DEFAULT_TURNTABLE_PORT = 54601

PATH_STATUS_IDLE = 1
PATH_STATUS_MOVING = 2

ROBOT_STATUS_ROOT = "RobotStatus"
AXIS_ANGLE_ROOT = "AxisAngle"
TURN_COMMAND_ROOT = "TurnCommand"

DEFAULT_HEARTBEAT_PERIOD_S = 0.2
DEFAULT_RECV_TIMEOUT_S = 0.2
DEFAULT_RECONNECT_DELAY_S = 1.0
DEFAULT_CONNECT_TIMEOUT_S = 3.0
