from __future__ import annotations

SETTINGS_SECTION_AXIS_TELEMETRY = "axisTelemetry"
SETTINGS_SECTION_ROBOT_PATH = "robotPath"
SETTINGS_SECTION_SCANNER_CONNECTION = "scannerConnection"
SETTINGS_SECTION_SDK_PATHS = "sdkPaths"
SETTINGS_SECTION_DEVICE_PARAMS = "deviceParams"
SETTINGS_SECTION_EXPOSURE_SETTINGS = "exposureSettings"
SETTINGS_SECTION_SCAN_PARAMS = "scanParams"
SETTINGS_SECTION_EXPOSURE_RANGE = "exposureRange"
SETTINGS_SECTION_PIPELINE_BEHAVIOR = "pipelineBehavior"
SETTINGS_SECTION_MESH_PARAMS = "meshParams"
SETTINGS_SECTION_PATHS = "paths"
SETTINGS_SECTION_PIPELINE = "pipeline"
SETTINGS_SECTION_LOGGING = "logging"

ALL_SETTINGS_SECTIONS = frozenset(
    {
        SETTINGS_SECTION_AXIS_TELEMETRY,
        SETTINGS_SECTION_ROBOT_PATH,
        SETTINGS_SECTION_SCANNER_CONNECTION,
        SETTINGS_SECTION_SDK_PATHS,
        SETTINGS_SECTION_DEVICE_PARAMS,
        SETTINGS_SECTION_EXPOSURE_SETTINGS,
        SETTINGS_SECTION_SCAN_PARAMS,
        SETTINGS_SECTION_EXPOSURE_RANGE,
        SETTINGS_SECTION_PIPELINE_BEHAVIOR,
        SETTINGS_SECTION_MESH_PARAMS,
        SETTINGS_SECTION_PATHS,
        SETTINGS_SECTION_PIPELINE,
        SETTINGS_SECTION_LOGGING,
    }
)

SCANNER_APPLY_SECTIONS = frozenset(
    {
        SETTINGS_SECTION_SDK_PATHS,
        SETTINGS_SECTION_DEVICE_PARAMS,
        SETTINGS_SECTION_EXPOSURE_SETTINGS,
        SETTINGS_SECTION_SCAN_PARAMS,
        SETTINGS_SECTION_EXPOSURE_RANGE,
    }
)

SAVE_ONLY_SCANNER_SECTIONS = frozenset(
    {
        SETTINGS_SECTION_PIPELINE_BEHAVIOR,
        SETTINGS_SECTION_MESH_PARAMS,
    }
)

SCANNER_SETTINGS_SECTIONS = SCANNER_APPLY_SECTIONS | SAVE_ONLY_SCANNER_SECTIONS
