SETTINGS_PREVIEW_PROJECT_NAME = "__settings_preview__"

SCAN_SAVE_TYPES = frozenset({"p3", "asc", "dgm"})
MESH_SAVE_TYPES = frozenset({"stl", "obj", "ply", "3mf"})

SDK_TIMEOUT_SEC = 120.0
SDK_CONNECT_MAX_ATTEMPTS = 30
SDK_CONNECT_RETRY_DELAY_SEC = 2.0
SDK_RESTART_DELAY_SEC = 2.5
SDK_INIT_MAX_ATTEMPTS = 3
SDK_INIT_RETRY_DELAY_SEC = 2.0
SDK_CONNECTING_WAIT_TIMEOUT_SEC = 10.0
SDK_SHUTDOWN_RELEASE_TIMEOUT_SEC = 15.0
SDK_EXIT_RELEASE_TIMEOUT_SEC = 5.0
SDK_PREAMBLE_RELEASE_TIMEOUT_SEC = 3.0
SDK_SESSION_SETTLE_SEC = 1.0

COMMAND_STILL_RUNNING_MARKER = "еще выполняется"


def is_scan_save_type(save_type: str) -> bool:
    return save_type.strip().lower() in SCAN_SAVE_TYPES
